import type { NextPage } from 'next'
import Head from 'next/head'
import Masterhead from '../components/Masterhead'
import AboutUs from '../components/AboutUs'
import Skills from '../components/Skilss'
import Tile from '../components/Tile'
import Works from '../components/Works'
import Footer from '../components/Footer'



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lorem Ipsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Masterhead />
      <AboutUs/>
      <Skills />
      <Tile />
      <Works />
      <Footer />
    </>
  )
}

export default Home
